### ISSUE TITLE
Using the Google Font

### ISSUE THREAD

**Issue by FlipperPA** [chadwhitman/chadwhitman.github.io#3]
The Google font may already be being distributed with Django. From django-developers:

The Google Font should not be an issue. We're already distributing that as part of the admin, which is installed by default. The page could just reference /static/admin/css/fonts.css

**Comment by collinanderson** [comment]
The font is here, by the way:
https://github.com/django/django/tree/master/django/contrib/admin/static/admin/fonts
https://github.com/django/django/blob/master/django/contrib/admin/static/admin/css/fonts.css

So `<link rel="stylesheet" href="/static/admin/css/fonts.css">` should just work.

**Comment by aaugustin** [comment]
Indeed, d.c.admin and d.c.staticfiles are enabled in the default project template, so we can piggyback on the admin static files.

It's slightly inelegant to use assets from the admin for the default page, but I believe this is a case where "praticality beats purity".

I suggest:
`<link rel="stylesheet" type="text/css" href="{% static "admin/css/fonts.css" %}" />`

For context, there are two reasons for doing this:

- privacy: don't make network requests to Google without the user's consent
- inclusivity: make it possible to use Django offline (not everyone trying Django has constant, fast access to the Internet)

These problems don't bother the majority of users, but it's trivial to avoid them.

**Comment by FlipperPA** [comment]
I've moved this to a local reference, thank you. I wasn't able to use {% static %} as it isn't available to the page; this is actually a basic HTML page without the static template tags available!
