### ISSUE TITLE
Auto-generate links for Django versions

### ISSUE THREAD

**Issue by FlipperPA** [chadwhitman/chadwhitman.github.io#5]
Figure out how to automagically have links update for the current Django version.

**Comment by FlipperPA** [comment]
>>> import django
>>> doc_version = '.'.join(django.get_version().split('.')[:2])
>>> doc_version
'1.8'

**Comment by chadwhitman** [comment]
thanks again @FlipperPA! This should work great. (also, this will probably be implemented once it is moved into Django...for now I'm just designing things via HTML/CSS (not on top of a Django install))...

**Comment by FlipperPA** [comment]
I've gotten this into place in the branch on the repository. I've also temporarily over-ridden the code to set version to equal "1.11", so we can test links that actually exist, since Django is already defaulting to "2.0". :)
