### ISSUE TITLE
Layout issues on small screens

### ISSUE THREAD

**Issue by FlipperPA** [chadwhitman/chadwhitman.github.io#7]
For what it's worth, I noticed a couple layout glitches in the current proposal, but nothing major:
- <main> can overlap <header> and <footer> at small heights e.g. with developer tools open at the bottom
- links look bad at 320px wide — try the "iPhone 5" setting in Chrome's responsive view

**Comment by chadwhitman** [comment]
Thanks for feedback. Commit 5eb0d80 should address both of these concerns. Feel free to pull and test (you may need to clear cache and close/open browser to see latest changes.
