### ISSUE TITLE
Increase font size for accessibility?

### ISSUE THREAD

**Issue by FlipperPA** [chadwhitman/chadwhitman.github.io#9]
For accessibility, I'd recommend to increase font size and width a bit. It's a bit hard to read on my older laptop.

**Comment by aaugustin** [comment]
+1 -- I have decent vision (with glasses) and an excellent screen, but found the text a bit difficult to read due to the relatively low font size and contrast.

Since there isn't a lot of content to fit on this page, it would be nice to make it highly legible.

**Comment by chadwhitman** [comment]
I increased the font size. I'll close for now, but reopen if it is still not big enough.
